######################################
#
# BUSCO summary figure
# @version 4.0.0
# @since BUSCO 2.0.0
# 
# Copyright (c) 2016-2023, Evgeny Zdobnov (ez@ezlab.org)
# Licensed under the MIT license. See LICENSE.md file.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("busco_summary_lepidoptera/","busco_figure.png",sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "BUSCO Assessment Results"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('GCF_012273895', 'GCF_012273895', 'GCF_012273895', 'GCF_012273895', 'GCF_905147765', 'GCF_905147765', 'GCF_905147765', 'GCF_905147765', 'Limnephilus_lunatus_v1_-_proteins', 'Limnephilus_lunatus_v1_-_proteins', 'Limnephilus_lunatus_v1_-_proteins', 'Limnephilus_lunatus_v1_-_proteins', 'GCF_905404315', 'GCF_905404315', 'GCF_905404315', 'GCF_905404315', 'GCF_905147365', 'GCF_905147365', 'GCF_905147365', 'GCF_905147365', 'GCA_905332375', 'GCA_905332375', 'GCA_905332375', 'GCA_905332375', 'GCF_001186105', 'GCF_001186105', 'GCF_001186105', 'GCF_001186105', 'GCA_933666425', 'GCA_933666425', 'GCA_933666425', 'GCA_933666425', 'GCF_000836215', 'GCF_000836215', 'GCF_000836215', 'GCF_000836215', 'GCF_905147795', 'GCF_905147795', 'GCF_905147795', 'GCF_905147795', 'GCF_009731565', 'GCF_009731565', 'GCF_009731565', 'GCF_009731565', 'GCF_023078275', 'GCF_023078275', 'GCF_023078275', 'GCF_023078275', 'GCF_000836235', 'GCF_000836235', 'GCF_000836235', 'GCF_000836235', 'GCF_905220565', 'GCF_905220565', 'GCF_905220565', 'GCF_905220565', 'GCF_023101765', 'GCF_023101765', 'GCF_023101765', 'GCF_023101765', 'GCF_905220365', 'GCF_905220365', 'GCF_905220365', 'GCF_905220365', 'GCF_003987935', 'GCF_003987935', 'GCF_003987935', 'GCF_003987935', 'GCF_014905235', 'GCF_014905235', 'GCF_014905235', 'GCF_014905235', 'GCF_014839805', 'GCF_014839805', 'GCF_014839805', 'GCF_014839805', 'GCA_902850265', 'GCA_902850265', 'GCA_902850265', 'GCA_902850265', 'GCF_905163445', 'GCF_905163445', 'GCF_905163445', 'GCF_905163445', 'GCF_004193835', 'GCF_004193835', 'GCF_004193835', 'GCF_004193835', 'GCF_932276165', 'GCF_932276165', 'GCF_932276165', 'GCF_932276165', 'GCA_933534255', 'GCA_933534255', 'GCA_933534255', 'GCA_933534255', 'GCF_905147045', 'GCF_905147045', 'GCF_905147045', 'GCF_905147045', 'GCF_024362695', 'GCF_024362695', 'GCF_024362695', 'GCF_024362695', 'GCF_002706865', 'GCF_002706865', 'GCF_002706865', 'GCF_002706865', 'GCF_902806685', 'GCF_902806685', 'GCF_902806685', 'GCF_902806685', 'GCF_905220415', 'GCF_905220415', 'GCF_905220415', 'GCF_905220415', 'GCA_921882275', 'GCA_921882275', 'GCA_921882275', 'GCA_921882275', 'GCF_002938995', 'GCF_002938995', 'GCF_002938995', 'GCF_002938995', 'GCA_918026875', 'GCA_918026875', 'GCA_918026875', 'GCA_918026875', 'GCA_902829305', 'GCA_902829305', 'GCA_902829305', 'GCA_902829305', 'GCF_905333055', 'GCF_905333055', 'GCF_905333055', 'GCF_905333055', 'GCF_003590095', 'GCF_003590095', 'GCF_003590095', 'GCF_003590095', 'GCF_003589595', 'GCF_003589595', 'GCF_003589595', 'GCF_003589595', 'GCA_902850365', 'GCA_902850365', 'GCA_902850365', 'GCA_902850365', 'GCF_023701775', 'GCF_023701775', 'GCF_023701775', 'GCF_023701775', 'GCF_905475465', 'GCF_905475465', 'GCF_905475465', 'GCF_905475465', 'GCA_907164705', 'GCA_907164705', 'GCA_907164705', 'GCA_907164705', 'GCF_912999745', 'GCF_912999745', 'GCF_912999745', 'GCF_912999745', 'GCF_905147105', 'GCF_905147105', 'GCF_905147105', 'GCF_905147105', 'GCA_916720795', 'GCA_916720795', 'GCA_916720795', 'GCA_916720795', 'GCA_902825455', 'GCA_902825455', 'GCA_902825455', 'GCA_902825455', 'GCF_022581195', 'GCF_022581195', 'GCF_022581195', 'GCF_022581195')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(length(levels(my_species)):1)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(93.9, 3.0, 0.5, 2.6, 99.2, 0.2, 0.2, 0.4, 30.8, 1.0, 9.3, 58.9, 95.3, 0.9, 0.6, 3.2, 97.6, 0.5, 0.1, 1.8, 96.5, 1.2, 0.5, 1.8, 97.3, 1.9, 0.4, 0.4, 95.4, 2.1, 1.0, 1.5, 96.4, 0.3, 1.7, 1.6, 98.0, 0.5, 0.2, 1.3, 97.4, 1.6, 0.3, 0.7, 90.5, 2.1, 0.7, 6.7, 99.5, 0.1, 0.1, 0.3, 97.7, 0.6, 0.2, 1.5, 98.3, 1.2, 0.1, 0.4, 99.2, 0.2, 0.1, 0.5, 93.9, 0.7, 0.3, 5.1, 97.9, 1.0, 0.2, 0.9, 91.5, 7.5, 0.2, 0.8, 92.1, 0.7, 1.8, 5.4, 98.5, 0.5, 0.1, 0.9, 97.4, 1.4, 0.6, 0.6, 98.3, 0.6, 0.1, 1.0, 78.8, 0.8, 5.5, 14.9, 98.8, 0.3, 0.1, 0.8, 97.6, 1.2, 0.1, 1.1, 98.8, 0.9, 0.2, 0.1, 98.1, 0.8, 0.2, 0.9, 98.8, 0.6, 0.1, 0.5, 97.5, 0.7, 0.5, 1.3, 99.0, 0.3, 0.2, 0.5, 91.4, 0.6, 2.3, 5.7, 90.4, 0.4, 0.9, 8.3, 97.9, 0.9, 0.1, 1.1, 92.9, 5.7, 0.2, 1.2, 94.7, 1.2, 1.1, 3.0, 88.9, 0.5, 0.6, 10.0, 94.3, 5.1, 0.0, 0.6, 97.4, 0.7, 0.1, 1.8, 94.1, 1.4, 1.9, 2.6, 98.7, 0.9, 0.1, 0.3, 97.6, 0.5, 0.2, 1.7, 95.1, 0.7, 1.1, 3.1, 92.2, 1.5, 0.9, 5.4, 99.1, 0.5, 0.1, 0.3)
my_values <- c(4966, 158, 25, 137, 5244, 9, 8, 25, 1626, 52, 490, 3118, 5038, 46, 33, 169, 5159, 24, 5, 98, 5099, 63, 27, 97, 5143, 99, 23, 21, 5043, 112, 54, 77, 5095, 14, 90, 87, 5179, 29, 8, 70, 5146, 84, 18, 38, 4786, 109, 39, 352, 5259, 6, 5, 16, 5164, 33, 8, 81, 5198, 66, 4, 18, 5242, 10, 4, 30, 4965, 35, 14, 272, 5175, 53, 10, 48, 4836, 397, 11, 42, 4871, 38, 97, 280, 5209, 25, 3, 49, 5147, 73, 34, 32, 5198, 33, 7, 48, 4168, 42, 291, 785, 5225, 16, 6, 39, 5161, 65, 3, 57, 5220, 46, 8, 12, 5188, 42, 11, 45, 5223, 32, 4, 27, 5153, 37, 25, 71, 5231, 14, 13, 28, 4829, 33, 119, 305, 4781, 20, 49, 436, 5176, 49, 6, 55, 4910, 301, 11, 64, 5007, 62, 58, 159, 4697, 26, 32, 531, 4986, 272, 1, 27, 5151, 36, 6, 93, 4974, 75, 98, 139, 5216, 49, 3, 18, 5158, 25, 10, 93, 5026, 37, 58, 165, 4873, 79, 45, 289, 5238, 28, 3, 17)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), position = position_stack(reverse = TRUE), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, hjust=0.5, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
print("Done")
