######################################
#
# BUSCO summary figure
# @version 4.0.0
# @since BUSCO 2.0.0
# 
# Copyright (c) 2016-2023, Evgeny Zdobnov (ez@ezlab.org)
# Licensed under the MIT license. See LICENSE.md file.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("teste_busco/","busco_figure.png",sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "BUSCO: Resultados para Endopterygota"

# Font
my_family <- "sans"
my_size_ratio <- 0.75

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('Colias_croceus', 'Colias_croceus', 'Colias_croceus', 'Colias_croceus', 'Danaus_Chrysippus', 'Danaus_Chrysippus', 'Danaus_Chrysippus', 'Danaus_Chrysippus', 'Nymphalis_io', 'Nymphalis_io', 'Nymphalis_io', 'Nymphalis_io', 'Bombyx_mandarina', 'Bombyx_mandarina', 'Bombyx_mandarina', 'Bombyx_mandarina', 'Pieris_rapae', 'Pieris_rapae', 'Pieris_rapae', 'Pieris_rapae', 'Ostrinia_furnacalis', 'Ostrinia_furnacalis', 'Ostrinia_furnacalis', 'Ostrinia_furnacalis', 'Bombyx_mori', 'Bombyx_mori', 'Bombyx_mori', 'Bombyx_mori', 'Leguminivora_glycinivorella', 'Leguminivora_glycinivorella', 'Leguminivora_glycinivorella', 'Leguminivora_glycinivorella', 'Spodoptera_littoralis', 'Spodoptera_littoralis', 'Spodoptera_littoralis', 'Spodoptera_littoralis', 'Helicoverpa_zea', 'Helicoverpa_zea', 'Helicoverpa_zea', 'Helicoverpa_zea', 'Amyelois_transitella', 'Amyelois_transitella', 'Amyelois_transitella', 'Amyelois_transitella', 'Limnephilus_lunatus', 'Limnephilus_lunatus', 'Limnephilus_lunatus', 'Limnephilus_lunatus', 'Leptidea_sinapis', 'Leptidea_sinapis', 'Leptidea_sinapis', 'Leptidea_sinapis', 'Vanessa_tameamea', 'Vanessa_tameamea', 'Vanessa_tameamea', 'Vanessa_tameamea', 'Danaus_plexippus_plexippus', 'Danaus_plexippus_plexippus', 'Danaus_plexippus_plexippus', 'Danaus_plexippus_plexippus', 'Helicoverpa_armigera', 'Helicoverpa_armigera', 'Helicoverpa_armigera', 'Helicoverpa_armigera', 'Zerene_cesonia', 'Zerene_cesonia', 'Zerene_cesonia', 'Zerene_cesonia', 'Chilo_suppressalis', 'Chilo_suppressalis', 'Chilo_suppressalis', 'Chilo_suppressalis', 'Arctia_plantaginis', 'Arctia_plantaginis', 'Arctia_plantaginis', 'Arctia_plantaginis', 'Papilio_polytes', 'Papilio_polytes', 'Papilio_polytes', 'Papilio_polytes', 'Aricia_agestis', 'Aricia_agestis', 'Aricia_agestis', 'Aricia_agestis', 'Papilio_xuthus', 'Papilio_xuthus', 'Papilio_xuthus', 'Papilio_xuthus', 'Euphydryas_editha', 'Euphydryas_editha', 'Euphydryas_editha', 'Euphydryas_editha', 'Pieris_brassicae', 'Pieris_brassicae', 'Pieris_brassicae', 'Pieris_brassicae', 'Hyposmocoma_kahamanoa', 'Hyposmocoma_kahamanoa', 'Hyposmocoma_kahamanoa', 'Hyposmocoma_kahamanoa', 'Spodoptera_exigua', 'Spodoptera_exigua', 'Spodoptera_exigua', 'Spodoptera_exigua', 'Maniola_hyperantus', 'Maniola_hyperantus', 'Maniola_hyperantus', 'Maniola_hyperantus', 'Vanessa_atalanta', 'Vanessa_atalanta', 'Vanessa_atalanta', 'Vanessa_atalanta', 'Iphiclides_podalirius', 'Iphiclides_podalirius', 'Iphiclides_podalirius', 'Iphiclides_podalirius', 'Pieris_napi', 'Pieris_napi', 'Pieris_napi', 'Pieris_napi', 'Pieris_macdunnoughi', 'Pieris_macdunnoughi', 'Pieris_macdunnoughi', 'Pieris_macdunnoughi', 'Plutella_xylostella', 'Plutella_xylostella', 'Plutella_xylostella', 'Plutella_xylostella', 'Manduca_sexta', 'Manduca_sexta', 'Manduca_sexta', 'Manduca_sexta', 'Diatraea_saccharalis', 'Diatraea_saccharalis', 'Diatraea_saccharalis', 'Diatraea_saccharalis', 'Maniola_jurtina', 'Maniola_jurtina', 'Maniola_jurtina', 'Maniola_jurtina', 'Trichoplusia_ni', 'Trichoplusia_ni', 'Trichoplusia_ni', 'Trichoplusia_ni', 'Pectinophora_gossypiella', 'Pectinophora_gossypiella', 'Pectinophora_gossypiella', 'Pectinophora_gossypiella', 'Melitaea_cinxia', 'Melitaea_cinxia', 'Melitaea_cinxia', 'Melitaea_cinxia', 'Papilio_machaon', 'Papilio_machaon', 'Papilio_machaon', 'Papilio_machaon', 'Spodoptera_litura', 'Spodoptera_litura', 'Spodoptera_litura', 'Spodoptera_litura', 'Parnassius_apollo', 'Parnassius_apollo', 'Parnassius_apollo', 'Parnassius_apollo', 'Pararge_aegeria', 'Pararge_aegeria', 'Pararge_aegeria', 'Pararge_aegeria', 'Spodoptera_frugiperda', 'Spodoptera_frugiperda', 'Spodoptera_frugiperda', 'Spodoptera_frugiperda', 'Brenthis_ino', 'Brenthis_ino', 'Brenthis_ino', 'Brenthis_ino', 'Vanessa_cardui', 'Vanessa_cardui', 'Vanessa_cardui', 'Vanessa_cardui')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(length(levels(my_species)):1)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(99.4, 0.4, 0.0, 0.2, 95.8, 0.5, 1.3, 2.4, 99.2, 0.2, 0.2, 0.4, 94.3, 0.6, 0.4, 4.7, 98.3, 0.6, 0.1, 1.0, 96.3, 1.1, 1.3, 1.3, 98.2, 1.2, 0.0, 0.6, 91.7, 1.8, 0.7, 5.8, 93.3, 0.7, 3.0, 3.0, 99.1, 0.6, 0.0, 0.3, 97.0, 2.2, 0.4, 0.4, 40.1, 0.7, 32.8, 26.4, 96.4, 0.8, 1.4, 1.4, 98.8, 0.3, 0.6, 0.3, 97.2, 1.8, 0.6, 0.4, 94.0, 5.3, 0.0, 0.7, 94.2, 3.0, 0.8, 2.0, 92.3, 0.4, 1.1, 6.2, 92.7, 1.1, 1.8, 4.4, 92.0, 0.2, 3.2, 4.6, 99.3, 0.3, 0.0, 0.4, 99.0, 0.2, 0.1, 0.7, 94.7, 1.5, 1.9, 1.9, 98.7, 0.3, 0.1, 0.9, 92.3, 1.2, 2.8, 3.7, 93.0, 0.5, 1.1, 5.4, 98.6, 0.8, 0.1, 0.5, 99.5, 0.0, 0.1, 0.4, 78.4, 0.3, 6.6, 14.7, 98.6, 0.4, 0.2, 0.8, 95.9, 0.8, 0.9, 2.4, 98.9, 0.6, 0.0, 0.5, 90.4, 8.7, 0.2, 0.7, 92.0, 0.5, 4.0, 3.5, 98.7, 0.7, 0.1, 0.5, 91.4, 7.2, 0.2, 1.2, 97.9, 1.6, 0.0, 0.5, 98.6, 0.4, 0.2, 0.8, 98.6, 1.1, 0.0, 0.3, 97.6, 1.0, 0.8, 0.6, 94.3, 1.0, 2.2, 2.5, 99.4, 0.2, 0.0, 0.4, 98.4, 1.1, 0.0, 0.5, 97.6, 0.1, 1.1, 1.2, 99.4, 0.2, 0.2, 0.2)
my_values <- c(2111, 9, 1, 3, 2034, 10, 28, 52, 2108, 5, 4, 7, 2003, 13, 8, 100, 2088, 12, 3, 21, 2046, 24, 27, 27, 2086, 26, 1, 11, 1947, 38, 15, 124, 1982, 15, 63, 64, 2105, 12, 0, 7, 2060, 46, 8, 10, 852, 15, 697, 560, 2048, 18, 29, 29, 2099, 7, 13, 5, 2065, 38, 13, 8, 1996, 113, 1, 14, 2001, 64, 17, 42, 1961, 9, 24, 130, 1969, 23, 39, 93, 1954, 4, 69, 97, 2110, 6, 1, 7, 2103, 5, 2, 14, 2011, 32, 40, 41, 2097, 6, 2, 19, 1961, 26, 59, 78, 1975, 10, 23, 116, 2094, 16, 3, 11, 2114, 1, 3, 6, 1666, 6, 140, 312, 2094, 8, 4, 18, 2036, 16, 20, 52, 2100, 12, 1, 11, 1920, 185, 5, 14, 1955, 11, 85, 73, 2097, 15, 2, 10, 1942, 152, 5, 25, 2079, 33, 1, 11, 2094, 9, 5, 16, 2095, 23, 1, 5, 2073, 22, 17, 12, 2002, 21, 47, 54, 2112, 5, 1, 6, 2091, 24, 1, 8, 2073, 3, 24, 24, 2111, 5, 4, 4)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), position = position_stack(reverse = TRUE), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, hjust=0.5, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(linewidth=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", linewidth = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
#ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
ggsave(file = "2_endopterygota.png", width = my_width, height = my_height, units = "cm", dpi = 300)
print("Done")
